'If you were in charge of a project or initiative from start to finish, skip “led” and instead try:'

'haired'
'Controlled'
'Coordinated'
'Executed'
'Headed'
'Operated'
'Orchestrated'
'Organized'
'Oversaw'
'Planned'
'Produced'
'Programmed'


Action Verbs 13-33
'You Envisioned and Brought a Project to Life' 
'And if you actually developed, created, or introduced that project into your company? Try:'

'Administered'
'Built'
'Charted'
'Created'
'Designed'
'Developed'
'Devised'
'Founded'
'Engineered'
'Established'
'Formalized'
'Formed'
'Formulated'
'Implemented'
'Incorporated'
'Initiated'
'Instituted'
'Introduced'
'Launched'
'Pioneered'
'Spearheaded'


Action Verbs 34-42
'You Saved the Company Time or Money'
'Hiring managers love candidates who’ve helped a team operate more efficiently or cost-effectively. To show just how much you saved, try:'

'Conserved'
'Consolidated'
'Decreased'
'Deducted'
'Diagnosed'
'Lessened'
'Reconciled'
'Reduced'
'Yielded'


Action Verbs 43-61
'You Increased Efficiency, Sales, Revenue, or Customer Satisfaction'
'Along similar lines, if you can show that your work boosted the company’s numbers in some way, you’re bound to impress. In these cases, consider:'

'Accelerated'
'Achieved'
'Advanced'
'Amplified'
'Boosted'
'Capitalized'
'Delivered'
'Enhanced'
'Expanded'
'Expedited'
'Furthered'
'Gained'
'Generated'
'Improved'
'Lifted'
'Maximized'
'Outpaced'
'Stimulated'
'Sustained'


Action Verbs 62-87
'You Changed or Improved Something'
'So, you brought your department’s invoicing system out of the Stone Age and onto the interwebs? Talk about the amazing changes you made at your office with these words:'

'Centralized'
'Clarified'
'Converted'
'Customized'
'Influenced'
'Integrated'
'Merged'
'Modified'
'Overhauled'
'Redesigned'
'Refined'
'Refocused'
'Rehabilitated'
'Remodeled'
'Reorganized'
'Replaced'
'Restructured'
'Revamped'
'Revitalized'
'Simplified'
'Standardized'
'Streamlined'
'Strengthened'
'Updated'
'Upgraded'
'Transformed'


Action Verbs 88-107
'You Managed a Team'
'Instead of reciting your management duties, like “Led a team…” or “Managed employees…” show what an inspirational leader you were with terms like:'

'Aligned'
'Cultivated'
'Directed'
'Enabled'
'Facilitated'
'Fostered'
'Guided'
'Hired'
'Inspired'
'Mentored'
'Mobilized'
'Motivated'
'Recruited'
'Regulated'
'Shaped'
'Supervised'
'Taught'
'Trained'
'Unified'
'United'


Action Verbs 108-113
'You Brought in Partners, Funding, or Resources'
'Were you “responsible for” a great new partner, sponsor, or source of funding? Try:''

'Acquired'
'Forged'
'Navigated'
'Negotiated'
'Partnered'
'Secured'


Action Verbs 114-122
'You Supported Customers'
'Because manning the phones or answering questions really means you’re advising customers and meeting their needs, use:'

'Advised'
'Advocated'
'Arbitrated'
'Coached'
'Consulted'
'Educated'
'Fielded'
'Informed'
'Resolved'


Action Verbs 123-142
'You Were a Research Machine'
'Did your job include research, analysis, or fact-finding? Mix up your verbiage with these words:'

'Analyzed'
'Assembled'
'Assessed'
'Audited'
'Calculated'
'Discovered'
'Evaluated'
'Examined'
'Explored'
'Forecasted'
'Identified'
'Interpreted'
'Investigated'
'Mapped'
'Measured'
'Qualified'
'Quantified'
'Surveyed'
'Tested'
'Tracked'


Action Verbs 143-161
'You Wrote or Communicated'
'Was writing, speaking, lobbying, or otherwise communicating part of your gig? You can explain just how compelling you were with words like:'

'Authored'
'Briefed'
'Campaigned'
'Co-authored'
'Composed'
'Conveyed'
'Convinced'
'Corresponded'
'Counseled'
'Critiqued'
'Defined'
'Documented'
'Edited'
'Illustrated'
'Lobbied'
'Persuaded'
'Promoted'
'Publicized'
'Reviewed'


Action Verbs 162-173
'You Oversaw or Regulated'
'Whether you enforced protocol or managed your department’s requests, describe what you really did, better, with these words:'

'Authorized'
'Blocked'
'Delegated'
'Dispatched'
'Enforced'
'Ensured'
'Inspected'
'Itemized'
'Monitored'
'Screened'
'Scrutinized'
'Verified'


Action Verbs 174-185
'You Achieved Something'
'Did you hit your goals? Win a coveted department award? Don’t forget to include that on your resume, with words like:'

'Attained'
'Awarded'
'Completed'
'Demonstrated'
'Earned'
'Exceeded'
'Outperformed'
'Reached'
'Showcased'
'Succeeded'
'Surpassed'
'Targeted'